stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - prod
  script:
    - docker compose down

deploy:
  stage: deploy
  tags:
    - prod
  script:
    - docker compose up -d
  only:
    - main