stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - prod
  script:
    - docker compose down
    - docker compose build --no-cache

deploy:
  stage: deploy
  tags:
    - prod
  script:
    - docker compose up 
  only:
    - dev