image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - prod
  script:
    - echo "DATABASE_URL=${DATABASE_URL}" >> .env
    - echo "BOT_TOKEN=${BOT_TOKEN}" >> .env
    - docker compose down
    - docker compose up -d --build
  only:
    - main