stages:
  - build
  - deploy

build:
  stage: build
  environment:
    name: prod
  tags:
    - prod
  script:
    - docker compose down
    - docker compose build --no-cache

deploy:
  stage: deploy
  environment:
    name: prod
  tags:
    - prod
  script:
    - docker compose up -d
  only:
    - main