version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_ENV=production
    entrypoint: npm run start:prod
    restart: always
    volumes:
      - .:/app
      - /app/node_modules