export enum BotScenes {
  MAIN_MENU = 'main-menu',
  MY_PROFILE = 'my-profile',
  MY_PETS = 'my-pets',
  REMAINERS = 'remainers',
  SETTINGS = 'settings',

  LANGUAGE = 'language',

  ADD_PET_NAME = 'add-pet-name',
  ADD_PET_TYPE = 'add-pet-type',
  ADD_PET_AGE = 'add-pet-age',
  ADD_PET_GENDER = 'add-pet-gender',
  ADD_PET_CONFIRM = 'add-pet-confirm',
  PET_DETAILS = 'pet-details',
  PET_EDIT = 'pet-edit',
  PET_DELETE = 'pet-delete',
  PET_LIST = 'pet-list',
  PET_ADD = 'pet-add',
  DELETE_PET = 'delete-pet',
  DELETE_PET_CONFIRM = 'delete-pet-confirm',

  REMINDERS_LIST = 'reminders-list',
  ADD_REMINDER_TITLE = 'add-reminder-title',
  ADD_REMINDER_DESCRIPTION = 'add-reminder-description',
  ADD_REMINDER_DATE = 'add-reminder-date',
  ADD_REMINDER_FREQUENCY = 'add-reminder-frequency',
  ADD_REMINDER_NOTIFY = 'add-reminder-notify',
  ADD_REMINDER_PETS = 'add-reminder-pets',
  ADD_REMINDER_CONFIRM = 'add-reminder-confirm',
  REMINDER_DETAILS = 'reminder-details',
  EDIT_REMINDER = 'edit-reminder',
  EDIT_REMINDER_DESCRIPTION = 'edit-reminder-description',
  EDIT_REMINDER_DATE = 'edit-reminder-date',
  EDIT_REMINDER_FREQUENCY = 'edit-reminder-frequency',
  EDIT_REMINDER_NOTIFY = 'edit-reminder-notify',
  DELETE_REMINDER_CONFIRM = 'delete-reminder-confirm',
}
